version: 2
updates:
  - package-ecosystem: "docker" 
    directory: "/xfinity-usage"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "pip"
    directory: "/xfinity-usage"
      interval: "weekly"
