version: 2
updates:
  - package-ecosystem: "docker" 
    directory: "/xfinity-usage"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "16:00"
      
  - package-ecosystem: "pip"
    directory: "/xfinity-usage"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "16:00"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "16:00"
