name: "Delete Old Packages"

on: 
  workflow_dispatch:
  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '0 0 * * 0' # Run Every Sunday

jobs:
  build:
    name: Delete Old Packages
    runs-on: ubuntu-latest
    permissions:
      packages: delete

      steps:      
      - name: Delete all untagged versions except latest 10
        uses: smartsquaregmbh/delete-old-packages@v0.8.1
        with:
          user: thor0215
          token: ${{ secrets.GITHUB_TOKEN }} 
          type: container
          names: |
            hassio-xfinity-usage-amd64
            hassio-xfinity-usage-aarch64
          version-pattern: ^sha256:.+$
          keep: 10
          dry-run: true

